<?php
$tt=0;
echo "<h1>Oops!!!! Time's Up........</h1>";
echo "<h1>Correct Answers are........</h1>";
echo "First Answer is";
echo"<br>";
echo "relatively easy to support in software";
echo"<br>";
echo"<br>";
echo "Secong Answer is";
echo"<br>";
echo "Operating System";
echo"<br>";
echo"<br>";
echo "Third Answer is";
echo"<br>";
echo "Accessories";
echo"<br>";
echo"<br>";
echo "Fourth Answer is";
echo"<br>";
echo "Windows NT";
echo"<br>";
echo"<br>";
echo "Fifth Answer is";
echo"<br>";
echo "WinZip";
echo"<br>";
echo"<br>";
echo "<h1>Your Score Is $tt</h1>";
echo"<br>";
echo "<a href='mainpage.php'>click here to go back</a>";
?>