<?php
$tt=0;
echo "<h1>Oops!!!! Time's Up........</h1>";
echo "<h1>Correct Answers are........</h1>";
echo "First Answer is";
echo"<br>";
echo "You can set different size for each recycle bin";
echo"<br>";
echo"<br>";
echo "Secong Answer is";
echo"<br>";
echo "You can restore any files in recycle bin if you ever need";
echo"<br>";
echo"<br>";
echo "Third Answer is";
echo"<br>";
echo "Control panel";
echo"<br>";
echo"<br>";
echo "Fourth Answer is";
echo"<br>";
echo "All of the above";
echo"<br>";
echo"<br>";
echo "Fifth Answer is";
echo"<br>";
echo "W3C";
echo"<br>";
echo"<br>";
echo "<a href='mainpage.php'>click here to go back</a>";
?>